### ISSUE TITLE
Missing Dependency `rubygems-foreman_api`

### ISSUE THREAD

**Issue by timfallmk** [theforeman/foreman-installer-staypuft#127]
The installer fails with the missing dependency on `rubygems-foreman_api`. I hunted around the repos and it doesn't seem to be there.

**Comment by jistr** [comment]
Hello :) If you can use Foreman's nightly repo, the package should be there:

http://yum.theforeman.org/nightly/el7/x86_64/

**Comment by mmoll** [comment]
can this get closed?

**Comment by ares** [comment]
I think so, staypuft is no longer supported. Anyone, please reopen if you disagree.
