### ISSUE TITLE
Conflicts between foreman-installer and staypuft firewall module files

### ISSUE THREAD

**Issue by matthewrees** [theforeman/foreman-installer-staypuft#149]
Hi there

I am using CentOS 7, EPEL 7 and the EL7 foreman-installer repo and I am seeing conflicts between foreman-installer-staypuft and foreman-installer for all of the files of foreman-installer's firewall module. Here is an excerpt from yum:

Transaction check error:
  file /usr/share/foreman-installer/modules/firewall/CHANGELOG.md conflicts between attempted installs of foreman-installer-staypuft-1:0.5.6-1.el7.noarch and foreman-installer-1:1.8.2-1.el7.noarch
  file /usr/share/foreman-installer/modules/firewall/CONTRIBUTING.md conflicts between attempted installs of foreman-installer-staypuft-1:0.5.6-1.el7.noarch and foreman-installer-1:1.8.2-1.el7.noarch
  file /usr/share/foreman-installer/modules/firewall/Gemfile conflicts between attempted installs of foreman-installer-staypuft-1:0.5.6-1.el7.noarch and foreman-installer-1:1.8.2-1.el7.noarch
  file /usr/share/foreman-installer/modules/firewall/README.markdown conflicts between attempted installs of foreman-installer-staypuft-1:0.5.6-1.el7.noarch and foreman-installer-1:1.8.2-1.el7.noarch
  file /usr/share/foreman-installer/modules/firewall/Rakefile conflicts between attempted installs of foreman-installer-staypuft-1:0.5.6-1.el7.noarch and foreman-installer-1:1.8.2-1.el7.noarch
  file /usr/share/foreman-installer/modules/firewall/checksums.json conflicts between attempted installs of foreman-installer-staypuft-1:0.5.6-1.el7.noarch and foreman-installer-1:1.8.2-1.el7.noarch
...
etc

I managed to resolve this by installing foreman-installer and all of foreman-installer-staypuft's dependencies first and then using "rpm -i --force" to install foreman-installer-staypuft manually.

I had the same issue on CentOS 6 with associated repos for EL6.

**Comment by ares** [comment]
this is on purpose, AFAIK staypuft is not compatible with Foreman 1.8+, it worked only with 1.7.

**Comment by matthewrees** [comment]
Aha, that would make sense. Thanks very much.

**Comment by jsuwo** [comment]
@ares "Worked"?  Does this imply this project is dying / dead?

**Comment by ares** [comment]
@jsuwo AFAIK yes, sadly...

**Comment by jsuwo** [comment]
@ares Thank you.
